/*
  Actions
    Lista de todas las acciones disponibles

Eduardo Muñoz López (eduardo@gestalabs.com)
10/02/2020
*/

export const GET_TOKEN_START = 'GET_TOKEN_START'
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS'
export const GET_TOKEN_FAIL = 'GET_TOKEN_FAIL'
export const LOGOUT = 'LOGOUT'

export const GET_MACHINES_START = 'GET_MACHINES_START'
export const GET_MACHINES_SUCCESS = 'GET_MACHINES_SUCCESS'
export const GET_MACHINES_FAIL = 'GET_MACHINES_FAIL'
export const NEW_MACHINE_STATUS = 'NEW_MACHINE_STATUS'

export const GET_VARIABLES_START = 'GET_VARIABLES_START'
export const GET_VARIABLES_SUCCESS = 'GET_VARIABLES_SUCCESS'
export const GET_VARIABLES_FAIL = 'GET_VARIABLES_FAIL'

export const GET_HISTORY_VALVE_START = 'GET_HISTORY_VALVE_START'
export const GET_HISTORY_VALVE_SUCCESS = 'GET_HISTORY_VALVE_SUCCESS'
export const GET_HISTORY_VALVE_FAIL = 'GET_HISTORY_VALVE_FAIL'
export const RESET_HISTORY = 'RESET_HISTORY'

export const ACTIVE_VARIABLE = 'ACTIVE_VARIABLE'
export const UPDATE_VARIABLE = 'UPDATE_VARIABLE'
export const UPDATE_VALVE = 'UPDATE_VALVE'

export const GET_HISTORY_VARIABLE_START = 'GET_HISTORY_VARIABLE_START'
export const GET_HISTORY_VARIABLE_SUCCESS = 'GET_HISTORY_VARIABLE_SUCCESS'
export const GET_HISTORY_VARIABLE_FAIL = 'GET_HISTORY_VARIABLE_FAIL'

export const GET_RANGES_START = 'GET_RANGES_START'
export const GET_RANGES_SUCCESS = 'GET_RANGES_SUCCESS'
export const GET_RANGES_FAIL = 'GET_RANGES_FAIL'

export const ACTIVE_RANGE = 'ACTIVE_RANGE'
export const UPDATE_RANGE = 'UPDATE_RANGE'
export const NEW_RANGE = 'NEW_RANGE'

export const GET_SCHEDULES_START = 'GET_SCHEDULES_START'
export const GET_SCHEDULES_SUCCESS = 'GET_SCHEDULES_SUCCESS'
export const GET_SCHEDULES_FAIL = 'GET_SCHEDULES_FAIL'

export const ACTIVE_SCHEDULE = 'ACTIVE_SCHEDULE'
export const NEW_SCHEDULE = 'NEW_SCHEDULE'
export const UPDATE_SCHEDULE = 'UPDATE_SCHEDULE'

export const SAVE_START = 'SAVE_START'
export const SAVE_SUCCESS = 'SAVE_SUCCESS'
export const SAVE_FAIL = 'SAVE_FAIL'
export const RESET_FORM = 'RESET_FORM'

export const GET_ALARMS_START = 'GET_ALARMS_START'
export const GET_ALARMS_SUCCESS = 'GET_ALARMS_SUCCESS'
export const GET_ALARMS_FAIL = 'GET_ALARMS_FAIL'

export const GET_SHUTDOWNS_START = 'GET_SHUTDOWNS_START'
export const GET_SHUTDOWNS_SUCCESS = 'GET_SHUTDOWNS_SUCCESS'
export const GET_SHUTDOWNS_FAIL = 'GET_SHUTDOWNS_FAIL'

export const ACTIVATE_ALARM = 'ACTIVATE_ALARM'
export const NEW_ALARM = 'NEW_ALARM'
export const UPDATE_ALARM = 'UPDATE_ALARM'

export const ACTIVATE_SHUTDOWN = 'ACTIVATE_SHUTDOWN'
export const NEW_SHUTDOWN = 'NEW_SHUTDOWN'
export const UPDATE_SHUTDOWN = 'UPDATE_SHUTDOWN'

export const MQTT_NEW_VARIABLE = 'MQTT_NEW_VARIABLE'
export const MQTT_CLIENT_CONNECT = 'MQTT_CLIENT_CONNECT'

export const GET_USERS_START = 'GET_USERS_START'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAIL = 'GET_USERS_FAIL'

export const NEW_USER = 'NEW_USER'
export const ACTIVE_USER = 'ACTIVE_USER'
export const UPDATE_USER = 'UPDATE_USER'
