# Generated by Django 2.1 on 2020-04-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
