# Generated by Django 2.1 on 2020-04-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_value_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
