# Generated by Django 2.1 on 2020-04-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0003_value_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='range',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
