version: '3.9'
services:
    api:
      stdin_open: true
      container_name: iot_monitoring_api
      restart: always
      build:
        context: ./backend
        dockerfile: Dockerfile
      volumes:
        - ./backend:/iot_monitoring_api
      ports:
        - "5000:5000"
      depends_on:
        - mysql
      environment:
        - FLASK_ENV=demo
        - DB_NAME=iot_monitoring_demo_db
        - DB_USER=iot_monitoring_demo_usr
        - DB_PASSWORD=iot_monitoring_demo_pwd
        - DB_HOST=iot_monitoring_mysql
        - DB_PORT=3306
      links:
        - mysql
    # dashboard:
    #   stdin_open: true
    #   container_name: iot_monitoring_dashboard
    #   build:
    #     context: ./dashboard
    #     dockerfile: Dockerfile
    #     network: host
    #   volumes:
    #     - ./dashboard:/app
    #     - /app/node_modules
    #   ports:
    #     - "3000:3000"
    #   environment:
    #     - CHOKIDAR_USEPOLLING=true
    #     - CI=true
    #     - REACT_APP_DASHBOARD_DOMAIN=${REACT_APP_DASHBOARD_DOMAIN}
    #     - REACT_APP_SIGMA_API=${REACT_APP_SIGMA_API}
    #     - REACT_APP_DASHBOARD_MACHINES_MODULE=${REACT_APP_DASHBOARD_MACHINES_MODULE}
    #     - REACT_APP_DASHBOARD_SCHEDULES_MODULE=${REACT_APP_DASHBOARD_SCHEDULES_MODULE}
    #     - REACT_APP_DASHBOARD_NOTIFICATION_MODULE=${REACT_APP_DASHBOARD_NOTIFICATION_MODULE}
    #     - REACT_APP_DASHBOARD_MANAGE_USERS_MODULE=${REACT_APP_DASHBOARD_MANAGE_USERS_MODULE}
    #     - REACT_APP_BROKER_HOST=${REACT_APP_BROKER_HOST}
    #     - REACT_APP_CODEX=${REACT_APP_CODEX}
    #   depends_on:
    #     - api
    #   links:
    #     - api
    #     - mosquitto
    mosquitto:
      image: eclipse-mosquitto
      container_name: iot_monitoring_mqtt
      restart: always
      build:
        context: ./mosquitto
        dockerfile: Dockerfile
        network: host
      ports:
        - "1883:1883"
        - "9001:9001"
      volumes:
        - ./volumes/mosquitto/data:/mosquitto/data
        - ./volumes/mosquitto/log:/mosquitto/log
    mysql:
      container_name: iot_monitoring_mysql
      restart: always
      build:
        context: ./mysql
        dockerfile: Dockerfile
      volumes:
        - ./volumes/mysql/data:/var/lib/mysql
        - ./mysql/my.cnf:/etc/my.cnf
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_USER=root
        - MYSQL_ROOT_PASSWORD=mysql_root_pwd
        - MYSQL_APP_DATABASE=iot_monitoring_demo_db
        - MYSQL_APP_USER=iot_monitoring_demo_usr
        - MYSQL_APP_PWD=iot_monitoring_demo_pwd


