# Generated by Django 2.1 on 2020-04-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0003_auto_20200227_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Proveedor'), (2, 'Operador'), (3, 'Administrador')], default=2),
        ),
    ]
