# Generated by Django 2.1 on 2020-04-08 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarm',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='shutdown',
            options={'ordering': ('-date',)},
        ),
    ]
