FROM node:16-alpine
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm install react-scripts@3.2.0 -g
# RUN npm install react-scripts@5.0.1 -g
RUN npm install

EXPOSE 3000

CMD ["npm", "start"]